name: Auto Create Release

on:
  push:
    branches:
      - main

jobs:
  check-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Check if version has changed
        id: check-version
        run: |
          git diff HEAD^ HEAD --name-only | grep "package.json" || echo "package.json not changed"
          if [[ $(git diff HEAD^ HEAD package.json | grep '"version":') ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Create Release
        if: steps.check-version.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: Release v${{ steps.package-version.outputs.current-version}}
          body: |
            Release of version ${{ steps.package-version.outputs.current-version}}
          draft: false
          prerelease: false
